[package]
name = "e-graph"
version = "0.1.0"
edition = "2024"

[dependencies]
egg = "0.10.0"
graphviz-rust = "0.9"
nom = "8"
parse_utils = { path = "../parse_utils" }
sml_utils = { path = "../sml_utils" }
