[package]
name = "skeleton"
version = "0.1.0"
edition = "2024"

[dependencies]
e-graph = { path = "../e-graph" }
mlton_ssa = { path = "../mlton_ssa" }
parse_utils = { path = "../parse_utils" }
nom = "8"
bimap = "0.6"