[package]
name = "skeleton"
version = "0.1.0"
edition = "2024"

[dependencies]
e-graph = { path = "../e-graph" }
sml_utils = { path = "../sml_utils" }
parse_utils = { path = "../parse_utils" }
nom = "8"
